### ISSUE TITLE
Documents (TMDL_Widget) - 6.21 - Link to view documents does not work

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#106]
When selecting the link to view a document, the file is not found. 

![image](https://cloud.githubusercontent.com/assets/8092133/5340813/c43e3bc6-7ebe-11e4-9f8f-ff34e9b34181.png)

![image](https://cloud.githubusercontent.com/assets/8092133/5340786/8782b3f6-7ebe-11e4-814f-c5953a09ee0b.png)

Steps to Recreate:
Select by: Site Selection > Tree Site Selection
Filter by: Geography > District 2 > Cecil
Site 0700003UT 
Document "AT0685582-EnvironDoc-20131216.pdf" - Server error 404 - file not found

**Comment by TaraF** [comment]
The issue here was that documentURL variable had been changed to a static value, instead of pulling from the config xml file like it had been previously:

Is: 
//documentURL = configXML.webservices.downloadservice;//TF updated
                documentURL = "http://localhost/DocumentManagement/";

should be:
documentURL = configXML.webservices.downloadservice;//TF updated
                //documentURL = "http://localhost/DocumentManagement/";

  I will need to build a new release of the flex code to correct this problem.  Please wait to test.

**Comment by TaraF** [comment]
Ready to test.

**Comment by BrittanyHuber** [comment]
tested on SHA network and it is working.
