### ISSUE TITLE
PHASE III - SHA DEV - long wait time when adding features

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#217]
When adding certain features the wait time is very long before the feature is added. The system does not present the user with any notifications that it is working on adding the feature, so the user may think its an error and will try to add the feature again. The system should notify the user that it is working on adding the feature in some way.

**Comment by BrittanyHuber** [comment]
@GraceAi - do you think the long wait time could be resolved at all or is it always going to take awhile for the system to add the feature?

**Comment by GraceAi** [comment]
@BrittanyHuber, I notice this issue happens when adding Eff BMP Retrofit Site Selection, Outfall Site Selection, Eff BMP strategy and Outfall strategy. Do you see if other assets have this issue? If not, I think the reason is that they use NPDES IDs to perform geoprocessing, which takes a long time. 

@ehsan67, is there any way to improve it?

**Comment by BrittanyHuber** [comment]
@GraceAi - the list you have is also what I have in my notes. All others seem to be fine.

**Comment by GraceAi** [comment]
Used a busy cursor to show the system is busy adding the feature. Need to update flex code.

**Comment by ehsan67** [comment]
I don't think we can do anything about it since it is related to geoprocessing

**Comment by BrittanyHuber** [comment]
tested in SHA DEV and the timer is working
