### ISSUE TITLE
AsBuilt Tracking (TMDL Widget) - 6.58.6 as built tracking fields

### ISSUE THREAD

**Issue by rmeitl** [dhenry-KCI/TMDL-_Tracking-Widget#79]
6.58.6
'As Built Status' and 'SHA Action' data doesn't show up for LUCHANGE_BMP features.
(Test Tree plantings: 130113UT or 160087UT)

They work fine for Efficiency BMPS (SWMFACs:  161033, 161031, 161028, 160929)

![untitled9](https://cloud.githubusercontent.com/assets/7804977/3543786/9c011220-0865-11e4-9ac4-b72e6861fd4f.jpg)

**Comment by ecomwu** [comment]
@ehsan67  
Ehsan, could you take a look at this issue? I thought that might be caused by data return issue. For the strategy selection type Tree plantings(130113UT or 160087UT) data return is different with Efficiency BMPS type. I provided the two links you can see the different:
http://vm-city102/TMDL/api/Strategies/GetAsBuilts?version=eGISW&format=xml&browsernocache=Thu%20Jul%2010%2017%3A20%3A27%20GMT-0400%202014&activityId=3AC3CFC3194E4833ACE43637BB9C988E 

http://vm-city102/TMDL/api/Strategies/GetAsBuilts?version=eGISW&format=xml&browsernocache=Thu%20Jul%2010%2017%3A14%3A39%20GMT%2D0400%202014&activityId=224973b9%2D5510%2D46e5%2Da625%2Dd28718628d19

**Comment by ehsan67** [comment]
@rmeitl @ecomwu The data is incorrect in the database. Some of the test records in AsBuilt table have description instead of domain key

**Comment by rmeitl** [comment]
ahh good catch @ehsan67 . thought i had checked that. Thanks - I'll fix the db!
