### ISSUE TITLE
Street Sweeping (TMDL-Widget) 6.30.6 - activity information associated to wrong activity table

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#99]
The system displays general information in the activity tab that is associated to the the TMDL Activity table, not the Sweeping Activity table. Fields listed in requirements document are for the associated SWEEPING_Activity table (fiscal year, total miles swept, swept by, date entered, plan achieved, username, general comments), however the fields in the widget are for the TMDL_Activity table.

![activity](https://cloud.githubusercontent.com/assets/8092133/4744087/32dbe44a-5a2d-11e4-954a-3e7137256afd.JPG)

Steps to recreate:
Select by form > TMDL Strategies > Street Sweeping
Filter by geography > District 4
Activity tab

**Comment by TaraF** [comment]
Hi Maggie,

Please take a look at this bug.  Please fix if you are able, or let us know if there was a reason we are using the general items under Activity here instead of in req 6.30.6.  If that is the case, can you send a quick reason and I will document it (this may be something you already worked out with Dustin). 

Thanks!
Tara

**Comment by ecomwu** [comment]
Hi Tara, 
The Activity always will display the information from TMDL activity table I guess. And for this specific strategy type, there is a tab call Actual Sweep will display related information.

Thanks,
Maggie
